/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutResponseDto
 */
export interface LogoutResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof LogoutResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the LogoutResponseDto interface.
 */
export function instanceOfLogoutResponseDto(value: object): value is LogoutResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function LogoutResponseDtoFromJSON(json: any): LogoutResponseDto {
    return LogoutResponseDtoFromJSONTyped(json, false);
}

export function LogoutResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function LogoutResponseDtoToJSON(json: any): LogoutResponseDto {
    return LogoutResponseDtoToJSONTyped(json, false);
}

export function LogoutResponseDtoToJSONTyped(value?: LogoutResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

