/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileDto } from './UserProfileDto';
import {
    UserProfileDtoFromJSON,
    UserProfileDtoFromJSONTyped,
    UserProfileDtoToJSON,
    UserProfileDtoToJSONTyped,
} from './UserProfileDto';

/**
 * 
 * @export
 * @interface MeResponseDto
 */
export interface MeResponseDto {
    /**
     * 
     * @type {UserProfileDto}
     * @memberof MeResponseDto
     */
    user: UserProfileDto;
}

/**
 * Check if a given object implements the MeResponseDto interface.
 */
export function instanceOfMeResponseDto(value: object): value is MeResponseDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function MeResponseDtoFromJSON(json: any): MeResponseDto {
    return MeResponseDtoFromJSONTyped(json, false);
}

export function MeResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserProfileDtoFromJSON(json['user']),
    };
}

export function MeResponseDtoToJSON(json: any): MeResponseDto {
    return MeResponseDtoToJSONTyped(json, false);
}

export function MeResponseDtoToJSONTyped(value?: MeResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserProfileDtoToJSON(value['user']),
    };
}

