/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicUserDto
 */
export interface PublicUserDto {
    /**
     * 
     * @type {string}
     * @memberof PublicUserDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUserDto
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicUserDto
     */
    role: string;
}

/**
 * Check if a given object implements the PublicUserDto interface.
 */
export function instanceOfPublicUserDto(value: object): value is PublicUserDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function PublicUserDtoFromJSON(json: any): PublicUserDto {
    return PublicUserDtoFromJSONTyped(json, false);
}

export function PublicUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'role': json['role'],
    };
}

export function PublicUserDtoToJSON(json: any): PublicUserDto {
    return PublicUserDtoToJSONTyped(json, false);
}

export function PublicUserDtoToJSONTyped(value?: PublicUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'role': value['role'],
    };
}

