/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMeDto
 */
export interface UpdateMeDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    birthDate?: string;
}

/**
 * Check if a given object implements the UpdateMeDto interface.
 */
export function instanceOfUpdateMeDto(value: object): value is UpdateMeDto {
    return true;
}

export function UpdateMeDtoFromJSON(json: any): UpdateMeDto {
    return UpdateMeDtoFromJSONTyped(json, false);
}

export function UpdateMeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'birthDate': json['birthDate'] == null ? undefined : json['birthDate'],
    };
}

export function UpdateMeDtoToJSON(json: any): UpdateMeDto {
    return UpdateMeDtoToJSONTyped(json, false);
}

export function UpdateMeDtoToJSONTyped(value?: UpdateMeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'birthDate': value['birthDate'],
    };
}

