/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    phone: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    firstName: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    lastName: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    birthDate: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    displayName: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDto
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    role: string;
}

/**
 * Check if a given object implements the UserProfileDto interface.
 */
export function instanceOfUserProfileDto(value: object): value is UserProfileDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserProfileDtoFromJSON(json: any): UserProfileDto {
    return UserProfileDtoFromJSONTyped(json, false);
}

export function UserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'phone': json['phone'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': json['birthDate'],
        'displayName': json['displayName'],
        'createdAt': (new Date(json['createdAt'])),
        'role': json['role'],
    };
}

export function UserProfileDtoToJSON(json: any): UserProfileDto {
    return UserProfileDtoToJSONTyped(json, false);
}

export function UserProfileDtoToJSONTyped(value?: UserProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'phone': value['phone'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': value['birthDate'],
        'displayName': value['displayName'],
        'createdAt': ((value['createdAt']).toISOString()),
        'role': value['role'],
    };
}

