/* tslint:disable */
/* eslint-disable */
/**
 * Blueprint API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MeResponseDto,
  UpdateMeDto,
} from '../models/index';
import {
    MeResponseDtoFromJSON,
    MeResponseDtoToJSON,
    UpdateMeDtoFromJSON,
    UpdateMeDtoToJSON,
} from '../models/index';

export interface UsersControllerUpdateMeRequest {
    updateMeDto: UpdateMeDto;
}

/**
 * 
 */
export class MeApi extends runtime.BaseAPI {

    /**
     */
    async usersControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async usersControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeResponseDto> {
        const response = await this.usersControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async usersControllerUpdateMeRaw(requestParameters: UsersControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeResponseDto>> {
        if (requestParameters['updateMeDto'] == null) {
            throw new runtime.RequiredError(
                'updateMeDto',
                'Required parameter "updateMeDto" was null or undefined when calling usersControllerUpdateMe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMeDtoToJSON(requestParameters['updateMeDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async usersControllerUpdateMe(requestParameters: UsersControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeResponseDto> {
        const response = await this.usersControllerUpdateMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
